version: '3.4'

services:
  hellodocker:
    image: hellodocker
    build:
      context: .
      dockerfile: HelloDocker/Dockerfile
  seonddockerapp:
    image: seonddockerapp
    build:
      context: .
      dockerfile: SeondDockerApp/Dockerfile
  helloworldworkerservice:
    image: helloworldworkerservice
    build:
      context: .
      dockerfile: HelloWorldWorkerService/Dockerfile